export const GET_SCREEN_WIDTH = "GET_SCREEN_WIDTH";

export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_TEMPORARY_USERNAME_UPON_SUCCESSFUL_REGISTRATION =
  "SET_TEMPORARY_USERNAME_UPON_SUCCESSFUL_REGISTRATION";
