export const GET_SCREEN_WIDTH = "GET_SCREEN_WIDTH";

export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_TEMPORARY_USERNAME_UPON_SUCCESSFUL_REGISTRATION =
  "SET_TEMPORARY_USERNAME_UPON_SUCCESSFUL_REGISTRATION";
export const UPDATE_USERNAME = "UPDATE_USERNAME";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
