// ---------ScreenWidth Actions----------
export const GET_SCREEN_WIDTH = "GET_SCREEN_WIDTH";

// ----------Auth Actions-----------
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_TEMPORARY_USERNAME_UPON_SUCCESSFUL_REGISTRATION =
  "SET_TEMPORARY_USERNAME_UPON_SUCCESSFUL_REGISTRATION";
export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const UPDATE_PORTFOLIO = "UPDATE_PORTFOLIO";

// ---------Profile Actions----------
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

// -----------Trade Actions------------
export const GET_ALL_COINS_WITH_AVATARS = "GET_ALL_COINS_WITH_AVATARS";
export const UPDATE_MY_COINS_LIST = "UPDATE_MY_COINS_LIST";
export const UPDATE_CURRENCY_ARRAY = "UPDATE_CURRENCY_ARRAY";
export const UPDATE_WALLET_VALUE = "UPDATE_WALLET_VALUE";
export const UPDATE_WALLET_VALUE_DIFFERENCE = "UPDATE_WALLET_VALUE_DIFFERENCE";
export const GET_PORTFOLIO = "GET_PORTFOLIO";
export const PORTFOLIO_LOADING = "PORTFOLIO_LOADING";
export const CLEAR_TRADE_OBJECT = "CLEAR_TRADE_OBJECT";

// ----------Errors Handling-----------
export const GET_ERRORS = "GET_ERRORS";
